print('a', end='')
print('_', '_', sep='b', end='c_')
print()
print('a', sep='_')
print('b', sep='_')
print('c', sep='_')
print()
print('a', 'b', 'c', sep='_', end='_')
print()
print('a', 'c', sep='_b_', end='_')
print()
print('a', '_', 'b', '_', 'c', end='_')